### ISSUE TITLE
Indexing fasta file containing multiple sequences

### ISSUE THREAD

**Issue by aedera** [vmiheer/nvbio#11]
Hello,

Thanks for this repo, the GPU implementation of Bowtie works excellent. However, I am experiencing an issue when using nvBWT to index a fasta file containing multiple sequences (i.e., multi-fasta format). Is it possible that nvBWT only indexes the first sequence that appears in an input multi-fasta file? What could I do to index such a file?

Thanks in advance.

**Comment by vmiheer** [comment]
Hello @aedera, I think you would like to look at https://www.nvidia.com/en-us/clara/genomics/ instead. I should archive this repo. https://github.com/NVIDIA-Genomics-Research/GenomeWorks

**Comment by aedera** [comment]
Thanks for the answer. I will have a look at Genome Works then.
